init 2:
    defineDynamicName fmName:
        name "Anne"
        shortname "Anne"
        informal "mom"
        formal "mother"
        role "mother"
        myformal "my mother"
        yourformal "your mother"
        myinformal "my mom"
        yourinformal "your mom"
        relation "family"
    defineDynamicName fsName:
        name "Juliette"
        shortname "Jules"
        informal "sis"
        formal "sister"
        role "sister"
        myformal "my sister"
        yourformal "your sister"
        myinformal "my sis"
        yourinformal "your sis"
        relation "family"